<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d3e1e47d-88d2-41f6-8479-9770cedc252e</testSuiteGuid>
   <testCaseLink>
      <guid>939ea6dd-c918-41d2-bc08-0dc329cdc600</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>48d80f4b-c3c2-4674-9ea2-493eb142cd25</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>48d80f4b-c3c2-4674-9ea2-493eb142cd25</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>294911ee-366e-48f3-8e19-8014f2b857e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>48d80f4b-c3c2-4674-9ea2-493eb142cd25</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>9939cede-7e18-4bbd-b9ef-1257eca54ec1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
